name: Build and Deploy QGIS Plugin

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools_scm
    
    - name: Update metadata version
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        python setup.py update .
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add */metadata.txt
        git commit -m "Update version to $TAG_VERSION in metadata.txt"
        git push
    
    - name: Build QGIS plugin
      run: |
        python setup.py build . -d dist -b build
    
    - name: Rename ZIP file
      run: |
        VERSION=$(grep "version=" */metadata.txt | cut -d= -f2 | tr -d '[:space:]')
        mv dist/*-${VERSION}.zip dist/PointCloudFR-${VERSION}.zip
    
    - name: Extract plugin version
      id: plugin_version
      run: |
        VERSION=$(grep "version=" */metadata.txt | cut -d= -f2 | tr -d '[:space:]')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    # Always upload as an artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: PointCloudFR-${{ steps.plugin_version.outputs.version }}
        path: dist/PointCloudFR-*.zip
        if-no-files-found: error
    
    # Only create a release when a tag is pushed
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/PointCloudFR-*.zip
        generate_release_notes: true
