name: Build and Deploy QGIS Plugin

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools_scm
          
      - name: Build QGIS plugin
        run: python setup.py build .
        
      # Upload the ZIP files directly, not the directory
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: PointCloudFR-plugin
          path: dist/*.zip
          if-no-files-found: error
          
      # For releases, use the already zipped file
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
          generate_release_notes: true
