name: Build and Deploy QGIS Plugin

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for setuptools_scm version detection
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools_scm
    
    - name: Update metadata version
      run: python setup.py update .
    
    - name: Build QGIS plugin
      run: python setup.py build . --update
    
    - name: Rename output file
      run: |
        mkdir -p dist
        mv dist/PointCloudFR-*.zip dist/PointCloudFR.zip
    
    - name: Extract plugin version
      id: plugin_version
      run: |
        VERSION=$(grep "version=" */metadata.txt | cut -d= -f2 | tr -d '[:space:]')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: PointCloudFR-${{ steps.plugin_version.outputs.version }}
        path: dist/PointCloudFR.zip
        if-no-files-found: error
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/PointCloudFR.zip
        generate_release_notes: true
