name: Build and Deploy QGIS Plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Format code base
        uses: pre-commit/action@v3.0.1  
        continue-on-error: true
        
      - name: Install build dependencies
        run: python -m pip install setuptools_scm
        
      - name: Build the QGIS plugin
        run: python setup.py build -u -d dist .
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: PointCloudFR-${GITHUB_REF_NAME}
          path: dist/*.zip
          if-no-files-found: error
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
          generate_release_notes: true 
      
