name: Build and Deploy QGIS Plugin

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Run pre-commit hooks (optional)
      - name: Format code base
        uses: pre-commit/action@v3.0.1
        continue-on-error: true

      # Create PR for pre-commit fixes if necessary
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          branch: pre-commit-fixes
          base: main

      # Install dependencies for building QGIS plugin
      - name: Install dependencies
        run: python -m pip install setuptools_scm

      # Build the QGIS plugin
      - name: Build the QGIS plugin
        run: python setup.py build

      # Upload build artifact if successful
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*.zip
          if-no-files-found: error

      # Create GitHub release if triggered by a tag push event
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.zip
          generate_release_notes: true
